USE master

ALTER DATABASE [{0}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE [{0}]
FROM DISK = N'{1}'
WITH FILE = 1
, MOVE N'{0}' TO N'D:\Temp\{0}.mdf'
, MOVE N'{0}_log' TO N'D:\Temp\{0}_1.ldf'
, NORECOVERY
, REPLACE 
, NOUNLOAD
, STATS = 10;

RESTORE DATABASE [{0}] WITH RECOVERY;

ALTER DATABASE [{0}] SET MULTI_USER;