USE [master]

ALTER DATABASE [{0}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

DECLARE @file VARCHAR(MAX)
SET @file = {1}
RESTORE DATABASE [{0}]
    FROM DISK = @file
    WITH REPLACE 

ALTER DATABASE [{0}] SET MULTI_USER;