USE [master]

ALTER DATABASE [{Database}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE [{Database}]
    FROM DISK = @Backup
    WITH REPLACE 

ALTER DATABASE [{Database}] SET MULTI_USER;